services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3dag5
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d project"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  project-manager:
    build: .
    container_name: project-manager
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "until pg_isready -h postgres-db -U postgres -d project; do echo waiting for db; sleep 2; done && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080 --proxy-headers"
    environment:
      DATABASE_URL: postgresql://postgres:3dag5@postgres-db:5432/project
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data:
