"""add constraint

Revision ID: 489a57caa991
Revises: 51729ec15902
Create Date: 2026-04-06 17:42:59.116679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import CheckConstraint


# revision identifiers, used by Alembic.
revision: str = '489a57caa991'
down_revision: Union[str, Sequence[str], None] = '51729ec15902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
     op.execute("""
        INSERT INTO employee (name, email, role)
        VALUES
        ('Admin', 'admin@test.com', 'System Admin'),
        ('Dagmawi', 'dagmawi@gmail.com', 'Dev'),
        ('Antehun', 'antehun@gmail.com', 'Designer')
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
